### ISSUE TITLE
Multiple selection is ambiguous when columns are fixed

### ISSUE THREAD

**Issue by dokato** [rstudio/DT#439] opened 2017-07-18 13:37 UTC
My problem is best described by this app:
```
library(shiny)

ui <-shinyUI(fluidPage(
  DT::dataTableOutput("tab"),
  title = "example"
))

server <- function (input, output) {
  m = as.data.frame(round(matrix(rnorm(1000), 50), 5))
  output$tab <- DT::renderDataTable(
    m, extensions = 'FixedColumns',
    options = list(
      scrollX = TRUE,
      fixedColumns = list(leftColumns = 2, rightColumns = 1)
    )
  )
  observeEvent(input$tab_rows_selected,{
    print(input$tab_rows_selected)
  })
}

shinyApp(ui=ui, server=server)
```

When I fix some columns and use multiselection, a frozen column can be selected as well. I think that expected behaviour would be to disable selection of fixed columns. Even when I select frozen columns it doesn't trigger any action.

Or maybe there is some way to disable that selection for particular columns?

![screen shot 2017-07-18 at 15 32 49](https://user-images.githubusercontent.com/4547289/28319524-6917148e-6bce-11e7-8118-79e4f3042c51.jpg)

**Comment by yihui** [comment] 2018-01-05 17:24
Duplicate of #275

**Closed** 2018-01-05 17:25 UTC
Labels: wontfix
