### ISSUE TITLE
When FixedColumns extension is used, only non-fixed columns are selected 

### ISSUE THREAD

**Issue by vzemlys** [rstudio/DT#378] opened 2016-12-13 08:14 UTC
Here is the reproducible example:

```
datatable(mtcars,extensions = "FixedColumns", options=list(scrollX = TRUE, scrollY=576, pagelength= 80,fixedColumns = TRUE),selection="single")
```

Click on the row and observe that the first column is not selected. If you click on the first column cell, then the cell is selected, but the remaining cells in the row are not selected. 

This behaviour can also be observed in https://rstudio.github.io/DT/extensions.html, see the FixedColumn extension examples and note that the row selection does not select all row.

**Comment by hitfuture** [comment] 2016-12-15 22:07
I'm seeing an identical issue with FixedColumns extension.

**Comment by yihui** [comment] 2018-01-05 17:12
Duplicate of #275

**Closed** 2018-01-05 17:25 UTC
Labels: wontfix
