### ISSUE TITLE
formatting functions should work for the Responsive plugin

### ISSUE THREAD

**Issue by andirey** [rstudio/DT#776] opened 2020-03-06 14:49 UTC
There is an extension for "datatables" in R called "Responsive". It adds the "green plus" button on the left side of the row. By clicking on it we can get the view with "hidden" columns.

Here is an example. 

The "visible" column "mpg_percents_visible" has correct format (3%) when "hidden" column "mpg_percents_hidden" has incorrect formatting in extended view (0.0326644890340644).

```
library(DT)

# 1. Data set
df_mtcars <- mtcars %>% 
  mutate(
    mpg_percents_visible = mpg / sum(mpg),
    mpg_percents_hidden = mpg / sum(mpg)) %>% 
  select(mpg_percents_visible, everything())

# 2. Datatable
datatable(df_mtcars, extensions = c('Responsive')) %>% 
  formatPercentage(c('mpg_percents_visible', 'mpg_percents_hidden'))
```

How show hidden column "mpg_percents_hidden" in a correct format (3%)?

Thanks!

**Comment by shrektan** [comment] 2020-03-07 19:14
The short answer is not possible by `DT::format***()` at present.

A note to myself, we may use [column.render()](https://datatables.net/reference/option/columns.render) to implement the format functions instead of using `rowCallback()`. It will then work for `Responsive` Plugin natively.

**Comment by stla** [comment] 2020-03-08 19:04
@shrektan As I noted [here](https://stackoverflow.com/questions/60564632/how-to-show-values-in-hidden-columns-for-datatable-r-in-a-correct-format/60566606#60566606) there's a potential gotcha with `column.render` as compared to `rowCallBack`.

**Comment by shrektan** [comment] 2020-03-09 01:28
Thanks. I didn’t notice that...

**Comment by shrektan** [comment] 2020-03-09 03:12
Well, I'm not sure what Colin really means [here](https://datatables.net/forums/discussion/55931/responsive-how-to-get-rendered-data-in-details-child-row) about the "data is static". This is also not documented on [column.render()](https://datatables.net/reference/option/columns.render). According to my experiments, I see everything works fine.

@stla Would you mind installing the version in PR #777 and do some tests for us? So that we can ensure #777 is safe enough to be merged, without breaking users' existing code.

Thanks.

> The only potential gotcha with this would be if something changes - columns.render is only called once and then cached, whereas that calculation in rowCallback is called on each draw. If the data is static, then what I suggested would be fine.

```r
library(shiny)
mkdata = function() {
  x = round(rnorm(100), 2L)
  tbl = data.frame(A = x, B = x, C = x)
  tbl
}
ui = basicPage(actionButton('add', "ADD"), DT::DTOutput('tbl'))
server = function(input, output) {
  output$tbl = DT::renderDT(
    datatable(mkdata(), extensions = c('Responsive'),
              options = list(scrollX = TRUE), editable = TRUE) %>% 
      formatPercentage(c('A', 'B', 'C'))
  )
  pxy = DT::dataTableProxy('tbl')
  observeEvent(input$add, {
    DT::replaceData(pxy, mkdata())
  })
}
shiny::runApp(list(ui = ui, server = server))
```

**Comment by andirey** [comment] 2020-03-10 06:26
Please, have a look at how the code above works [https://ibb.co/mzmk9wh](test). It seems a problem  with formatting hidden columns remain

**Comment by shrektan** [comment] 2020-03-10 06:31
I don't know what you mean. You are claiming that you don't find your original example work even if you are using the latest dev version of DT?

 (run `remotes::install_github('rstudio/DT')` to install the dev version of DT)

**Comment by andirey** [comment] 2020-03-10 13:54
The latest dev version of DT seems workable. Thanks!

**Comment by shrektan** [comment] 2020-03-10 14:20
> Is it possible to fix this bug for CRAN version as well?

There’re CRAN releasing cycles usually one or two months. 

> Updates for dev version bring me error on datatables.

I don’t know what you mean.

**Comment by yihui** [comment] 2020-03-10 14:24
I can do a CRAN release soon, but I also want to understand what this means first:

> Updates for dev version bring me error on datatables.

**Comment by andirey** [comment] 2020-03-10 15:42
After I made `remotes::install_github('rstudio/DT')` the hidden columns have correct formatting. But this message appears during loading datatable: "DataTables warning: table id=DataTables_Table_2 - Requested unknown parameter '6' for row 0, column 6. For more information about this error, please see http://datatables.net/tn/4".

So, I reinstall CRAN version to avoid it, and CRAN version has incorrect formatting of hidden columns. Will be glad to make DT reinstallation from CRAN soon.

Thanks!

**Comment by shrektan** [comment] 2020-03-10 15:51
I’m afraid it may due to the recent commits. Releasing to CRAN doesn’t solve this. Would you mind take some time to provide us a minimal reproducible example? So that we can know what’s going on before the release in case of affecting our users.

**Comment by andirey** [comment] 2020-03-10 15:52
Yes, I will try to it.

**Comment by yihui** [comment] 2020-03-17 02:03
I'm going to reopen this issue and wait for @andirey's reproducible example before making a CRAN release.

**Comment by andirey** [comment] 2020-03-17 16:44
Hi @yihui! Thanks for re-opening this issue.
There is a bug in processing "NA" issues for hidden columns.
I added "2. Bug emulation" line of code. So, if you run this code - you will a warning message like
"DataTables warning: table id=xxx - Requested unknown parameter '6' for row 0, column 6. 
For more information about this error, please see http://datatables.net/tn/4".

In my case, I just impute missing values by zeros but it can't be correct in general.
The empty value is looking better.

```
library(DT)

# 1. Data set
df_mtcars <- mtcars %>% 
  mutate(
    mpg_percents_visible = mpg / sum(mpg),
    mpg_percents_hidden = mpg / sum(mpg)) %>% 
  select(mpg_percents_visible, everything())

# 2. Bug emulation
df_mtcars[2, ]$mpg_percents_hidden <- NA

# 3. Datatable
datatable(df_mtcars, extensions = c('Responsive')) %>% 
  formatPercentage(c('mpg_percents_visible', 'mpg_percents_hidden'))

```
Hope CRAN release will not have this bug.

**Comment by shrektan** [comment] 2020-03-18 01:57
@andirey Thanks so much for your reproducible example. we've identified the cause and it should be fixed when the PR gets merged.

**Comment by andirey** [comment] 2020-03-18 08:37
Hi, @shrektan ! Please, ping me when it will be fixed as well. I have a big R / R Shiny project and would like to fix this bug as well. The best solution will be to get an empty string for "formatPercentage" and other "formatXXX" operators when the value of feature is NA. Right now I start using zero instead NA but it's incorrect. Will be happy to get updates of DT from CRAN!

**Closed** 2020-03-19 20:04 UTC
Labels: enhancement, extensions
