### ISSUE TITLE
Upload to CRAN

### ISSUE THREAD

**Issue by csgillespie** [rstudio/DT#259] opened 2016-04-01 09:04 UTC
I've created a new [RStudio addin](https://github.com/csgillespie/addinmanager) for managing addin installation. However, it depends in DT >= 0.1.3. 

When do you think CRAN DT will be updated?

**Comment by yihui** [comment] 2016-04-10 06:02
Duplicate of #191. My current guess is the end of this month. Thanks for your patience!

**Closed by yihui** 2016-04-10 06:02 UTC
