### ISSUE TITLE
Ajax Error with Load Balancer on Chrome

### ISSUE THREAD

**Issue by jdonnell01** [rstudio/DT#642] opened 2019-03-07 14:44 UTC
I recently implemented a load balancer for my R Shiny application with two separate instances of the application running. On occasion when I navigate to the load balancer URL I see the following JS alert:

DataTables warning: table id=DataTables_Table_0 - Ajax error. For more information about this error, please see http://datatables.net/tn/7

In the console I see a 404 Not Found error on all my datatable objects. I am using S3 and grabbing all of my .rds files when the application loads. All other objects load as expected except those that will be rendered as a datatable. This only seems to occur on Chrome and only happens about 25% of the time - the error seems quite erratic. Is this a known issue or has anyone seen this happen before?

**Comment by shrektan** [comment] 2019-03-08 06:28
A simple workaround for your case is to use client mode for all your DT tables (if your table is not too big to use client mode). 

As for the cause, it seems like the AJAX request is forwarded to the wrong worker, which I suppose is tied to your load balancer implementations.

**Comment by shrektan** [comment] 2019-03-08 18:07
This is called sticky session or persistent session in load rebalancing.

**Comment by jdonnell01** [comment] 2019-03-08 18:10
Thank you - I will try this out. To confirm, by client mode you are referring the the below:

`datatable(mtcars, rownames = FALSE, options = list(ajax = list(serverSide = FALSE)))`

**Comment by shrektan** [comment] 2019-03-09 00:44
No, `renderDT(..., server=False)`

**Comment by jdonnell01** [comment] 2019-03-12 22:18
Thank you. Does disabling server-side processing affect how datatable proxies are created? I create a proxy of one of my tables for further manipulation and this downstream process seems to be breaking now that I set the original table to server = FALSE.

**Comment by shrektan** [comment] 2019-03-12 23:28
No, it should not. Please test it on local. If there’s still a problem, a reproducible example is welcomed. Thanks.

**Comment by lengyuyeke** [comment] 2019-03-13 03:03
I see this problem too . It occurs a few seconds after I open the page .
When I checkout the problem, it shows the post request return a `404 not found ` error.

**Comment by jdonnell01** [comment] 2019-03-13 22:08
Hi @shrektan. After further investigation I see that the rows_selected functionality is actually operating correctly, but rather I instantiated an action button that when clicked will select the appropriate row in the datatable which is failing:

```
observe({
  lapply (1:length(unique(my_dt$FIELD)), function (i) {
      proxy = dataTableProxy('TABLE1')
      proxy %>% selectRows(as.numeric(i))
  })
})
```

**Comment by shrektan** [comment] 2019-03-14 05:25
The following code works for me. If you still have problems, please provide a minimal reproducible example so that we can help. Thanks.

```r
library(shiny)

ui <- fluidPage(
  actionButton('select', 'select'),
  DT::DTOutput('tbl')
)
server <- function(input, output, session) {
  output$tbl <- DT::renderDT(iris, server = FALSE)
  proxy <- DT::dataTableProxy('tbl')
  observeEvent(input$select, {
    DT::selectRows(proxy, sample(1:10, 1))
  })
}

shiny::runApp(mget(c('ui', 'server')))
```

**Comment by jdonnell01** [comment] 2019-03-26 19:58
Hello @shrektan. Your example does not seem to be working for me. I included a text output to your example to print the current selected row and when I set server=FALSE there is no text output, however when server=TRUE it seems to select a random row.

`library(shiny)

ui <- fluidPage(
  actionButton('select', 'select'),
  DT::DTOutput('tbl'),
  htmlOutput('selectedrow')
)
server <- function(input, output, session) {
  output$tbl <- DT::renderDT(iris, server = FALSE)
  proxy <- DT::dataTableProxy('tbl')
  observeEvent(input$select, {
    DT::selectRows(proxy, sample(1:10, 1))
  })
  output$selectedrow <- renderText(input$tbl_rows_selected)
}

shiny::runApp(mget(c('ui', 'server')))`

**Comment by jdonnell01** [comment] 2019-04-01 13:30
Hi @shrektan. Just following up here - would you constitute this as a bug?

**Comment by shrektan** [comment] 2019-04-01 14:42
No, both versions work on my computer. Are you sure you are using the latest version of DT? If not, please install and re-test it by running `remotes::install_github('Rstudio/DT')`.

If still had problems, please paste your `sessionInfo()` here. Thanks.

**Comment by jdonnell01** [comment] 2019-04-01 15:24
Thank you - I will test with the latest version. Are you able to update CRAN with the latest version?

**Comment by yihui** [comment] 2019-04-01 15:50
We can update DT on CRAN this month if it would fix your issue.

**Comment by jdonnell01** [comment] 2019-04-01 22:37
Thank you - this seems to be working now. One final question - now that I have flipped my tables to client-side processing and try to filter on columns it is extremely slow (~15 - 20 seconds to respond). Is there any way to mitigate this slowless?

**Comment by shrektan** [comment] 2019-04-01 23:23
I’m afraid not. 

Anyway, generally it should be fast enough unless your table contains dozens of columns and you are using IE...

**Comment by jdonnell01** [comment] 2019-04-01 23:51
The table contains 8 columns, however I am using IE. Are there any steps to remediate for IE use?

**Comment by shrektan** [comment] 2019-04-02 03:32
So your table contains tons of characters or thousands of rows? For small datasets, it should be fast. However, on some old computers, using IE is just 10 times slower.

I can only suggest you:

- Update your IE version (not sure if related but you can try to disable the compatible view mode),
- Use server processing mode,
- Or, use Chrome.

**Comment by jdonnell01** [comment] 2019-04-02 14:25
There are actually only 10 columns and roughly 700 rows. Understood - if there is any way to mitigate the ajax load balancer error without switching to client-side processing I will do that. Is that possible?

**Comment by shrektan** [comment] 2019-04-02 15:31
IMHO, you need to configure the sticky sessions for your load balancer. If you are using Nginx, add ip_hash to the directive should be enough (I never test this but should be easy to google)...

**Comment by jdonnell01** [comment] 2019-04-02 16:41
I actually did enable sticky sessions on my load balancer and still got the error. I am not sure how DT works under the hood but is it possible that IE is caching the responses from the Ajax requests from the other worker which is causing the error? So essentially the session string that it caches is from the other worker (and due to Access-Control-Allow-Origin not being enabled) results in the 404 Not Found. Can I possibly prevent this caching from here https://datatables.net/reference/option/ajax.data? Again, I am not sure if this is the case - I would need to test to validate. Just a thought.

**Comment by shrektan** [comment] 2019-04-02 23:21
I think sticky session means the request from the same up will always be directed to the same worker. 

DT uses the Javascript library DataTables. in the server processing mode, it uses AJAX to get the data from the server. In my opinion, it should have nothing to do with caches or access-control-allow-origin. However, I haven’t tried to use a load balancer so this is the best I can help. 

You should google "Datatables load balancer server processing" if you’d like further investigation.

**Comment by laz08** [comment] 2020-04-10 10:08
Hi,

aside from loading the data client-side, is there any workaround for this?

I have got this error too and it also happens randomly around 25% of the time. I've debugged as instructed at https://datatables.net/manual/tech-notes/7 and the data loads just fine until it doesn't, returning a 404, requesting to the same URL. 

I don't think the solution of loading the data client-side works for me, as my data is around 1.000.000 rows and 20 columns.

Any feedback or brainstorming is welcome, since I've been struggling with this for over a week...

Thanks

**Comment by shrektan** [comment] 2020-04-10 13:46
@laz08  Do you use a load balancer? It sounds so. Please enable the sticky session of the load balancer as suggested in the above comment. I don't know any other options. 

The bottom line is that it must be the same worker that hosts your shiny application and responds to the AJAX request DT sends out.

**Comment by shrektan** [comment] 2020-10-05 18:04
Hi, everyone, I have created a docker-swarm based example at https://github.com/shrektan/DT-load-balancer .

At least, according to my experiments, DT works correctly when sticky session is set up correctly in the load balancer.

So I'm closing this issue.

For more details, please check [the demo repo](https://github.com/shrektan/DT-load-balancer) as mentioned above.

**Closed by shrektan** 2020-10-05 18:04 UTC
Labels: load-balancer, question

**Comment by mpereira-dev** [comment] 2022-07-29 14:41
For me the Datatables Ajax issue was a combination of the Load Balancer (AWS ALB) sticky session cookie and the Content Delivery Network (AWS CloudFront).

I've also seen the Ajax issue when the Shiny app crashes and the session information is not available.
And when a connection request or response request times out.

IMHO the datatables package should to better error handling on the Ajax request.

For example, it **should not** pop up a modal dialogue for each visible table. This creates a frustrating user experience.
It would be much better if the HTML were the tables are generally rendered instead render a message indicating the data is not available because the session information could not be found on the server or there was a communication problem etc.

And an error could be printed on the web console with additional recommendations and debugging information.

This issue stumped me for quite a while. I wouldn't have made significant progress without a big hint from the AWS support team.

I ended up moving all static assets to S3 so they don't have to go through the ALB and disabled caching on all other requests. That seems to have (mostly) cleared up the issue.
