### ISSUE TITLE
`datatable` widget isn't anchored correctly to parent when used in `renderDataTable()`

### ISSUE THREAD

**Issue by landroni** [rstudio/DT#590] opened 2018-09-10 03:18 UTC
I usually encounter this issue in a `flexdashboard` document with `vertical_layout: fill`. 

When using `datatable()` _outside_ a reactive context, the `datatable` object will usually be anchored correctly to the parent widget. By that I mean that the `datatable` widget will be correctly scaled to fit the parent widget, and will be resized to fit the parent when the window is resized, etc. This makes the `datatable` widget always in sync with the parent, like this: 

    ---
    title: "MRE"
    author: ""
    output: 
      flexdashboard::flex_dashboard:
        orientation: columns
        vertical_layout: fill
    runtime: shiny
    ---
    
    
    
    Page 1 {data-orientation=columns}
    =======================================================================
    
    Column {data-width=650}
    -----------------------------------------------------------------------
    
    ### Tab 1
    
    ```{r}
    # DT::renderDataTable({  ##uncomment to reproduce bug
        DT::datatable(mtcars, 
                      filter = 'top',
                      extensions = c('Scroller'),
                      options = list(scrollY=600, 
                                     scrollX=300, 
                                     scroller = TRUE,
                                     deferRender = TRUE,
                                     pageLength = 250))
    # })  ##uncomment to reproduce bug
    
    ```
    
    
    Column {data-width=650}
    -----------------------------------------------------------------------
    
    ### Tab 2
    
Here's how it renders in the app: 
![screenshot_2018-09-09_19-44-28](https://user-images.githubusercontent.com/1318567/45273735-d6508600-b468-11e8-8e6e-2cf8d79eb0ac.png)

Notice how the DT widget is sized so that it occupies all the available space within the tab. 

--------
Now uncomment the lines in the code above, so that the R chunk reads like this: 

    ```{r}
    DT::renderDataTable({  ##uncomment to reproduce bug
        DT::datatable(mtcars, 
                      filter = 'top',
                      extensions = c('Scroller'),
                      options = list(scrollY=600, 
                                     scrollX=300, 
                                     scroller = TRUE,
                                     deferRender = TRUE,
                                     pageLength = 250))
    })  ##uncomment to reproduce bug
    ```

Notice now how the DT widget is no longer in sync with the parent widget: however you resize the window, the widget is going to stay stuck at a fixed size. 
![screenshot_2018-09-09_19-56-20](https://user-images.githubusercontent.com/1318567/45274047-722ec180-b46a-11e8-8335-4134d60da88b.png)

This is problematic with end-users, since people use different screen resolutions, so for some the static widget size will be too small; while for others it will overflow the window -- like in the screenshot above -- and the horizontal scrollbars won't be visible, thus making it unusable, etc.

Is this an issue with DT? How can I work around this within a reactive context? 

-----

```
> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.0
LAPACK: /usr/lib/lapack/liblapack.so.3.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.18          digest_0.6.15         rprojroot_1.3-2       jsonlite_1.5         
 [5] backports_1.1.2       magrittr_1.5          evaluate_0.10.1       stringi_1.1.6        
 [9] DT_0.4                rmarkdown_1.10        flexdashboard_0.5.1.1 tools_3.4.4          
[13] stringr_1.2.0         htmlwidgets_1.0       yaml_2.1.16           compiler_3.4.4       
[17] htmltools_0.3.6       knitr_1.19           
```

**Comment by shrektan** [comment] 2018-09-28 15:04
Thanks for the reporting. I haven't looked into the root causes but you can use the param `fillContainer = TRUE` in the reactive context. See the full example below. 

````Rmd
---
title: "MRE"
author: ""
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

Page 1 {data-orientation=columns}
=======================================================================

Column {data-width=650}
-----------------------------------------------------------------------

### Tab 1

```{r}
DT::renderDataTable({ 
  ####################### USE THE PARAM fillContainer = TRUE ######3
    DT::datatable(mtcars, fillContainer = TRUE)
})
```

Column {data-width=650}
-----------------------------------------------------------------------

### Tab 2

````

<img width="542" alt="image" src="https://user-images.githubusercontent.com/8368933/46216680-bd096e00-c372-11e8-943d-2c60e6a91071.png">

**Comment by landroni** [comment] 2018-09-29 17:05
That's perfect, thanks! 

I guess I should have read the docs more carefully, but it was unclear where the issue was actually arising, so I just wrote it down to unexpected behavior.

**Comment by shrektan** [comment] 2020-02-05 18:31
Looks the issue has been solved already. Closing it.

**Closed by shrektan** 2020-02-05 18:31 UTC

**Comment by AnotherDataGuy** [comment] 2021-03-19 15:26
Sorry if I am off topic but how can you achieve the same result when using only flexdashboard (without Shiny)?

fillContainer = TRUE doesn't seems to adjust when I change the screen.

```

---
title: "Title"
output:
  flexdashboard::flex_dashboard:
    vertical_layout: fill
    theme: united
editor_options: 
  chunk_output_type: inline
---

```
```{r}
library(DT)
library(flexdashboard)
```
```

Section 1
=====================================


Column{.tabset .tabset-fade}
-------------------------------------

### Nice table {data-height="100%"}

```
```{r}
datatable(mtcars,
  rownames = F,
  class = "cell-border stripe",
  extensions = c("Buttons", "Select", "SearchPanes", "FixedColumns"),
  selection = "none",
  filter = "top",
  callback = JS("$.fn.dataTable.ext.errMode = 'none';"),
  options = list(
    autoWidth = T,
    dom = "Bfrt",
    pageLength = length(mtcars),
    columnDefs = list(
      list(width = "140px", targets = list(0, 1, 2, 3)),
      list(width = "300px", targets = list(4)),
      list(width = "400px", targets = list(5, 6, 7)),
      list(visible = FALSE, targets = list(10))
    ),
    searchHighlight = TRUE,
    buttons = c("csv", "excel", "pdf"),
    scrollX = 1000,
    scrollY = 500,
    fillContainer = TRUE,
    scroller = TRUE,
    # pageResize = T,
    deferRender = TRUE,
    scrollCollapse = T,
    callback = JS("$.fn.dataTable.ext.errMode = 'none';")
  )
)
```
```

```
Thanks!
