### ISSUE TITLE
DT prints "blank" table in RStudio in certain editor themes

### ISSUE THREAD

**Issue by lrdegeest** [rstudio/DT#781] opened 2020-03-18 01:05 UTC
Working in RStudio 1.2.5033 with the built-in Monokai theme. 

I ran  the "hello world" for `DT`: 

```
library(DT)
datatable(iris)
```

and saw an empty table:

<img width="899" alt="Screen Shot 2020-03-17 at 8 44 56 PM" src="https://user-images.githubusercontent.com/10857097/76915074-8db22e00-6892-11ea-99bc-93acae5879ae.png">

but when I ran my mouse over it I saw the table values were printed in white:

<img width="898" alt="Screen Shot 2020-03-17 at 8 45 13 PM" src="https://user-images.githubusercontent.com/10857097/76915096-9dca0d80-6892-11ea-8589-906cf710e32b.png">

When I changed the background to Textmate the table printed fine:

<img width="1003" alt="Screen Shot 2020-03-17 at 8 57 47 PM" src="https://user-images.githubusercontent.com/10857097/76915176-d833aa80-6892-11ea-9118-87226c7424f9.png">

I get the same behavior with the CRAN and GitHub versions of the package. Does `DT` only work with certain editor themes in RStudio?

**Comment by shrektan** [comment] 2020-03-18 01:21
Thanks for reporting but it's duplicate of #447 . 

The cause is tricky - the RStudio theme will change the table's color attributes but not able to change the background attributes, as the background is hard-coded to "black". 

I'm afraid a solution without affecting the existing users is only possible after the sass feature being implemented, when DT is able to adjust the CSS attributes dynamically according to the context. See more discussions on #767 .

**Comment by lrdegeest** [comment] 2020-03-18 01:46
Ok thanks!

**Closed** 2020-03-19 20:10 UTC
Labels: duplicate
