### ISSUE TITLE
Shiny Copy button with html formatting

### ISSUE THREAD

**Issue by YaoDaoCSU** [rstudio/DT#445] opened 2017-08-11 16:16 UTC
I am using the copy buttons in DT package in a R shiny app. The button is working properly, however, my tables involves html formatting within each cell, but when I copy that using the copy button, the html formatting disappears. Is there a way to copy the tables as they show up in the browser (i.e. with html formatting)?
 The table that I am trying to copy would be something similar to the following:
```
outputTable = data.frame(row.names = c("<b>Row 1</b>", "&emsp;Row2<br> &emsp;&emsp;Level1<br> &emsp;&emsp;Level2"), Column1 = c("", "<br>100(10)<br>200 (20)" ))
    colnames(outputTable) = "Column 1 <br> N = 100"
```

**Comment by shrektan** [comment] 2020-02-01 17:17
Sorry for the late reply. Unfortunately, there's nothing we can do to help because the extension will only use the raw data. Duplicate of #449.

**Closed by shrektan** 2020-02-01 17:17 UTC
