### ISSUE TITLE
Multiple Currency Symbols in formatCurrency

### ISSUE THREAD

**Issue by mark-fastpay** [rstudio/DT#308] opened 2016-06-14 19:08 UTC
Would it be possible to enable one to pass a vector of currency symbols for each row than having only one currency for all rows in formatCurrency?  Sometimes I need to show different currency symbols for different line items in an app that I am working on.

Thanks,
Mark

**Comment by shrektan** [comment] 2016-06-23 15:03
Why not convert it to `character` in advance?

**Comment by mark-fastpay** [comment] 2016-06-23 16:44
Main problem is once I convert to character, the sorting doesn’t work
correctly.  Is it possible to manually mark a character column to sort and
search like a number / currency column?  That would also achieve my end
goal about as well.



*From:* Xianying Tan [mailto:notifications@github.com]
*Sent:* Thursday, June 23, 2016 8:03 AM
*To:* rstudio/DT <DT@noreply.github.com>
*Cc:* Mark Baran <mark@gofastpay.com>; Author <author@noreply.github.com>
*Subject:* Re: [rstudio/DT] Multiple Currency Symbols in formatCurrency
(#308)



Why not convert it to character in advance?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rstudio/DT/issues/308#issuecomment-228078945>, or mute
the thread
<https://github.com/notifications/unsubscribe/AGzWzPgzBIRV4N6UWUL_tf1nSZTpb-KTks5qOqAlgaJpZM4I1qD9>
.

**Comment by shrektan** [comment] 2016-07-02 03:13
OK. But will it make too much sense to sort if the currency itself is different? Another bypass solution would be insert the currency symbols into a separated column.

**Comment by yihui** [comment] 2016-07-22 21:09
Duplicate of #273.

**Closed by yihui** 2016-07-22 21:09 UTC
Labels: duplicate
