### ISSUE TITLE
DT unable to display data.table::ITime columns

### ISSUE THREAD

**Issue by JenspederM** [rstudio/DT#840] opened 2020-08-13 13:31 UTC
I receive the following error when data contain columns created by `data.table::IDateTime`:

> DataTables warning: table id=DataTables_Table_0 - Ajax error. For more information about this error, please see http://datatables.net/tn/7

I have read through the documentation at the suggested link, but I am unable to resolve the error. Debugging in browser reveals that the error is a server error - and from the console I get the following message:

> Warning: Error in vapply: values must be length 4,
 but FUN(X[[3]]) result is length 1
  [No stack trace available]

Oddly enough, it works when I use the `shiny::renderDataTable / shiny::dataTableOutput`, though with unwanted integer conversion of the ITime when it is the only column. As shown, `DT` render `IDate` columns well enough - but is completely unable to render `ITime` columns. 

Is there any way around this problem?

``` r
library(data.table)
library(shiny)
library(DT)
#> 
#> Vedhæfter pakke: 'DT'
#> De følgende objekter er maskerede fra 'package:shiny':
#> 
#>     dataTableOutput, renderDataTable

shinyApp(
  ui = basicPage(
    fluidRow(
      column(width = 6, h3("IDatetime [DT]"), DT::dataTableOutput("tab1")),
      column(width = 6, h3("IDateTime [shiny]"), shiny::dataTableOutput("tab2"))
    ),
    br(),
    hr(),
    br(),
    fluidRow(
      column(width = 6, h3("IDate [DT]"), DT::dataTableOutput("tab3")),
      column(width = 6, h3("IDate [shiny]"), shiny::dataTableOutput("tab4"))
    ),
    br(),
    hr(),
    br(),
    fluidRow(
      column(width = 6, h3("ITime [DT]"), DT::dataTableOutput("tab5")),
      column(width = 6, h3("ITime [shiny]"), shiny::dataTableOutput("tab6"))
    )
  ),
  server = function(input, output) {
    data_idatetime = data.table(
      IDateTime(c("2020-08-13 10:00:00", "2020-08-13 10:00:00", "2020-08-13 10:00:00", "2020-08-13 10:00:00"))
    )
    
    data_idate = data.table(
      idate = as.IDate(c("2020-08-13", "2020-08-13", "2020-08-13", "2020-08-13"))
    )
    
    data_itime = data.table(
      itime = as.ITime(c("10:00:00", "10:00:00", "10:00:00", "10:00:00"))
    )
    
    output$tab1 = DT::renderDataTable({
      data_idatetime
    })
    
    output$tab2 = shiny::renderDataTable({
      data_idatetime
    })
    
    output$tab3 = DT::renderDataTable({
      data_idate
    })
    
    output$tab4 = shiny::renderDataTable({
      data_idate
    })
    
    output$tab5 = DT::renderDataTable({
      data_itime
    })
    
    output$tab6 = shiny::renderDataTable({
      data_itime
    })
  }
)
#> 
#> Listening on http://127.0.0.1:5989
```

![](https://i.imgur.com/TPBE4OO.png)

``` r

xfun::session_info()
#> R version 4.0.2 (2020-06-22)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 17134)
#> 
#> Locale:
#>   LC_COLLATE=Danish_Denmark.1252  LC_CTYPE=Danish_Denmark.1252   
#>   LC_MONETARY=Danish_Denmark.1252 LC_NUMERIC=C                   
#>   LC_TIME=Danish_Denmark.1252    
#> 
#> Package version:
#>   base64enc_0.1.3   BH_1.72.0.3       callr_3.4.3       commonmark_1.7   
#>   compiler_4.0.2    crayon_1.3.4      crosstalk_1.1.0.1 data.table_1.13.0
#>   digest_0.6.25     DT_0.15           evaluate_0.14     fastmap_1.0.1    
#>   glue_1.4.1        graphics_4.0.2    grDevices_4.0.2   highr_0.8        
#>   htmltools_0.5.0   htmlwidgets_1.5.1 httpuv_1.5.4      jsonlite_1.7.0   
#>   knitr_1.29        later_1.1.0.1     lazyeval_0.2.2    magrittr_1.5     
#>   markdown_1.1      methods_4.0.2     mime_0.9          processx_3.4.3   
#>   promises_1.1.1    ps_1.3.3          R6_2.4.1          Rcpp_1.0.5       
#>   rlang_0.4.7       rmarkdown_2.3     shiny_1.5.0       sourcetools_0.1.7
#>   stats_4.0.2       stringi_1.4.6     stringr_1.4.0     tinytex_0.25     
#>   tools_4.0.2       utils_4.0.2       webshot_0.5.2     withr_2.2.0      
#>   xfun_0.16         xtable_1.8-4      yaml_2.2.1
```

<sup>Created on 2020-08-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by shrektan** [comment] 2020-08-13 14:46
The cause of this issue, I believe, is that the `toJSON()` function can't handle ITime objects.

```r
DT:::toJSON(data.table::IDateTime('2020-01-01 12:00'))
# {"idate":["2020-01-01"],"itime":{}} 
```

**Comment by JenspederM** [comment] 2020-08-13 19:38
That seems right.  Should I post in htmlwidgets as well?

**Comment by shrektan** [comment] 2020-08-15 03:51
The method for ITime should be registered for `jsonlite:::asJSON()`. I'll see if I can file a PR later.

**Comment by shrektan** [comment] 2020-08-17 11:28
This is fixed in the dev version of jsonlite. 

You can test it via `remotes::install_github('jeroen/jsonlite')`.

Thanks again for the report.

**Closed by shrektan** 2020-08-17 11:28 UTC
Labels: enhancement
