### ISSUE TITLE
Data Tables not displaying in Shiny with new version of DT

### ISSUE THREAD

**Issue by naturofix** [rstudio/DT#562] opened 2018-06-22 17:20 UTC
When trying to view dataTableOutput in R shiny I get the following error

```
DataTables warning: table id=DataTables_Table_7 - Error in `[<-.data.frame`(`*tmp*`, , j, value = c(0.9, NA, NA, NA, NA, : replacement has 196 rows, data has 4
```

In the shiny ui : `dataTableOutput('multi_patient_table_wide')`

In the shiny server : 
```
  output$multi_patient_table_wide = renderDataTable({
    print('multi_patient_table_wide')
    df = patient_data()[patient_data()$MRN %in% input$multi_plot_patients,]
    df
  })

```

I am able to view the data frame in Rstudio. I can upload a .rds file of this table if necessary. 

When downgrading to previous versions of DT, version 0.2, I do not have this issue.

**Comment by yihui** [comment] 2018-06-22 18:50
Could you provide [a minimal, self-contained, and reproducible example](https://yihui.name/en/2017/09/the-minimal-reprex-paradox/)?

**Comment by JohnPugs** [comment] 2018-09-06 22:36
We have a somewhat similar issue. Except, the first row value is being duplicated for all rows in the column. Also, when we sort with the up/down arrows, the value in the column #1 changes.

**Comment by shrektan** [comment] 2020-02-01 17:19
Close this since no further response. Feel free to reopen with a reproducible example. Thanks!

**Closed by shrektan** 2020-02-01 17:19 UTC
