### ISSUE TITLE
dataTableOutput() example not working

### ISSUE THREAD

**Issue by Mullefa** [rstudio/DT#79] opened 2015-05-26 12:05 UTC
Hi,

I am executing the following code (copy and pasted from the example `?dataTableOutput`) in my browser (Google Chrome):

```R
if (interactive()) {
  library(shiny)
  shinyApp(
    ui = fluidPage(fluidRow(column(12, DT::dataTableOutput('tbl')))),
    server = function(input, output) {
      output$tbl = DT::renderDataTable({
        DT::datatable(iris, options = list(lengthChange = FALSE))
      })
    }
  )
}
```

A new tab opens, however, it is blank.

Here is my session info:

```
Session info -------------------------------------------------------------------------
 setting  value                       
 version  R version 3.1.2 (2014-10-31)
 system   x86_64, darwin10.8.0        
 ui       RStudio (0.98.1091)         
 language (EN)                        
 collate  en_GB.UTF-8                 
 tz       Europe/London               

Packages -----------------------------------------------------------------------------
 package     * version   date       source        
 bitops      * 1.0-6     2013-08-17 CRAN (R 3.1.0)
 devtools    * 1.7.0     2015-01-17 CRAN (R 3.1.2)
 digest      * 0.6.8     2014-12-31 CRAN (R 3.1.2)
 DT            0.0.50    2015-05-26 local (/@)    
 evaluate    * 0.5.5     2014-04-29 CRAN (R 3.1.0)
 formatR     * 1.0       2014-08-25 CRAN (R 3.1.1)
 htmltools   * 0.2.6     2014-09-08 CRAN (R 3.1.1)
 htmlwidgets * 0.4.2     2015-05-26 local (/@)    
 httpuv      * 1.3.2     2014-10-23 CRAN (R 3.1.2)
 httr        * 0.6.1     2015-01-01 CRAN (R 3.1.2)
 jsonlite    * 0.9.14    2014-12-01 CRAN (R 3.1.2)
 knitr       * 1.9       2015-01-20 CRAN (R 3.1.2)
 magrittr    * 1.5       2014-11-22 CRAN (R 3.1.2)
 mime        * 0.3       2015-03-29 CRAN (R 3.1.3)
 R6          * 2.0.1     2014-10-29 CRAN (R 3.1.2)
 Rcpp        * 0.11.5    2015-03-06 CRAN (R 3.1.3)
 RCurl       * 1.95-4.5  2014-12-06 CRAN (R 3.1.2)
 rstudio     * 0.98.1091 2015-01-13 local         
 rstudioapi  * 0.2       2014-12-31 CRAN (R 3.1.2)
 shiny         0.12.0    2015-05-18 CRAN (R 3.1.3)
 stringr     * 0.6.2     2012-12-06 CRAN (R 3.1.0)
 vepr        * 0.0.2     2015-04-09 local         
 xtable      * 1.7-4     2014-09-12 CRAN (R 3.1.1)
 yaml        * 2.1.13    2014-06-12 CRAN (R 3.1.0)
```

**Comment by yihui** [comment] 2015-05-26 18:12
I just tested it on Mac, and it worked well for me (in both RStudio and Chrome). Do you see any error messages in the JavaScript console (from the menu `More tools -> JavaScript console`)?

I'm using R 3.2.0 and RStudio 0.99 (http://www.rstudio.com/products/rstudio/download/). That is a possible reason for me being unable to reproduce your issue.

**Comment by Mullefa** [comment] 2015-05-26 20:50
I'll get matching versions of R and RStudio at work tomorrow tomorrow, and see if the issue persists.

**Comment by yihui** [comment] 2015-05-26 21:17
If you can open the JavaScript console as I mentioned above, and tell me the error messages (if there are any), I may also come up with a fix. Thanks!

**Comment by Mullefa** [comment] 2015-05-27 07:01
If I inspect element and go to console, I see the following error:

```
Uncaught TypeError: Cannot read property 'data' of undefined    datatables.js:5
```

If I click on the `datatables.js:5` link, the erroneous source code is displayed:

```js
HTMLWidgets.widget({
  name: "datatables",
  type: "output",
  renderValue: function(el, data) {
    var $el = $(el), cells = data.data;
    $el.empty();
...
```

(line 5 underlined in red). Having basically no knowledge of javascript I don't know if this information is sufficient, so please let me know if you need additional information. Cheers.

**Comment by yihui** [comment] 2015-05-27 17:36
Thanks! You don't need to know anything about JavaScript. The error message is helpful to me. Perhaps it is the insufficient version of jsonlite. Hmm. How were you able to install htmlwidgets after all?... (since we specified `jsonlite (>= 0.9.16)` in htmlwidgets) Anyway, when in doubt, try `update.packages(ask = FALSE)`, and see if the problem goes away.

**Comment by Mullefa** [comment] 2015-05-27 20:19
If I recall correctly, I installed `htmlwidgets` via `devtools::install_github()`.

I have just updated `jsonlite`, and good news! I now have a beautiful table rendered in my browser.

Cheers for your help.

**Comment by Mullefa** [comment] 2015-05-27 20:20
Sorry, didn't mean to close the issue, but feel free to - it's sorted as far as I'm concerned :D

**Comment by yihui** [comment] 2015-05-27 20:27
Okay, it sounds like it is indeed an issue of an insufficient version of jsonlite. Thanks for the confirmation.

P.S. No worries about closing the issue. I like it when a user closes an issue by oneself.

P.P.S. Your Github profile picture looks familiar to me. From Princess Mononoke, right? :)

**Closed by yihui** 2015-05-27 20:27 UTC
Labels: question

**Comment by Mullefa** [comment] 2015-05-27 20:53
It is indeed :D
