### ISSUE TITLE
DT not showing in shiny when executed from a .bat

### ISSUE THREAD

**Issue by aandradep** [rstudio/DT#613] opened 2018-10-23 22:30 UTC
I have a large shiny that uses Shiny extensively. When i was developing it it work perfect when I run it from the server.r. But now i want to deploy the shiny with a  very simple .bat that execute the run.r script in r. 

The .bat file has the following code: "C:\Program Files\R\R-3.5.1\bin\R.exe" CMD BATCH "run.r". The problem is that if I run then shiny app with the bat file non of the DT appear in the shiny. 

The space is left blank but and inspecting the web page (it opens in google chrome) it does not have the java script code that that i get when running the shiny app from the server.r file. I saw that this was a problem of the 0.3 version but i currently have the 0.4 version,

This is a reproduzable example:

### server.r:

```r
server <- function(input, output,session) {
  observeEvent(input$run,{
TablasVaR <- function(mat,DT = T){

      mat_tbl <- data.frame(Activos = rownames(mat),Porcentaje = mat[,"Porcentaje"],
                            VaR = mat[,"Nivel"])
      
      tabla <- datatable(mat_tbl, escape = T,rownames = FALSE, 
                         selection = list(target = 'row'),
                         options = list(dom = 'tip', paging = TRUE))%>%
        formatStyle(1:ncol(mat_tbl),fontSize = '100%')%>%
        formatCurrency(3,digits = 0)%>%
        formatPercentage(2,digits = 1)
      if(DT){
        return(tabla)
      } else{
        return(mat_tbl)
      }
      
    }
    
    matr <- data.frame(Porcentaje=rnorm(19),Nivel = rnorm(19))
  output$table <- renderDataTable({TablasVaR(matr)})
  })
  session$onSessionEnded(function() {
    stopApp()
  })  
}
```

### ui.r:

```r
ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(),
    wellPanel(style = "background-color: #ffffff;",
              bsButton("run","run1",block=F, style="default"),
              fluidRow(column(4,align="center",offset = 4,
                              dataTableOutput("table"))))
  ))
```

run.r:

```r
librerias <- c("openxlsx","ggplot2","scales","rugarch","zoo","data.table","stringr",
               "DT","plotly","lubridate","knitr","gridExtra","grid","shinyBS",
               "rmarkdown","nloptr","shiny")
if(length(setdiff(librerias, rownames(installed.packages()))) > 0){
  install.packages(setdiff(librerias, rownames(installed.packages())))
}
invisible(sapply(librerias, require, character.only = TRUE))

CAMINO <<- "D:/Users/aandr/Documents/Ejemplo/"
runApp(CAMINO, launch.browser=TRUE)
```

### .bat:
`"C:\Program Files\R\R-3.5.1\bin\R.exe" CMD BATCH "run.r"`

**Comment by shrektan** [comment] 2018-10-24 08:11
I use DT everyday on my computer using the the batch script and never had a problem.

We'd like to help but would you mind make the example [not only "reproducible" but also "minimal"](https://yihui.name/en/2017/09/the-minimal-reprex-paradox/) ? Like there're bunch of the unused libraries and most of the settings are unrelated to the problem.

After that, if the problem still occurs, please paste your session info here. Thanks.

**Comment by aandradep** [comment] 2018-10-24 13:04
Thats true i had a put all the libraries that i'm using in my actual shiny app because i wasn't able to reproduce the error with out theme.  It took my a wile but if you replace the variable librerias for:
librerias <- c("DT","shinyBS","shiny")
the error keeps happening.

**Comment by shrektan** [comment] 2018-11-17 14:16
All the CSS stuff is unrelated to the problem. Moreover, what error happens?

Without details, I cannot help. What I can guess is, are you sure the R version you use on Batch mode is the same you use in RStudio? You are using R3.5.1 it suggests that you reinstall the R recently.

**Comment by shrektan** [comment] 2019-03-16 17:18
Close this issue since there's no further response.

**Closed by shrektan** 2019-03-16 17:18 UTC
