### ISSUE TITLE
Frozen Header Appearing on All Tabs

### ISSUE THREAD

**Issue by tsouchlarakis** [rstudio/DT#432] opened 2017-06-20 01:22 UTC
I noticed that with the option `fixedHeader = TRUE`, the frozen header will appear on all tabs of a Shiny app. Here is an example illustrating the problem. Simply go to "Tab2" and scroll down, and the header from "Tab1" should be visible (unwanted). I would like the header to only appear on "Tab1".

```
library(shiny)
library(DT)

data("volcano")

ui = shinyUI(navbarPage(title = 'Navbar',
  tabPanel('Table',
           fluidPage(
             fluidRow(
               column(width = 12,
                      DT::dataTableOutput('table'))
               )
           )
  ),
  
  tabPanel('Tab2',
           fluidPage(
             fluidRow(
               column(width = 4,
                      style = "height:1500px;background-color:#f0f0f5;border-radius:6px 0px 0px 6px;
                      box-shadow:1px 1px 8px #888888")
             )
           )
  )
))

server = shinyServer(function(input, output){
  output$table <- DT::renderDataTable(
    volcano,
    extensions = c('Buttons', 'FixedHeader'),
    options = list(
      pageLength = 100,
      fixedHeader = TRUE
    )
  )
})

runApp(list(ui=ui, server=server), launch.browser = TRUE)
```

**Comment by yihui** [comment] 2018-01-16 06:11
Duplicate of #389

**Closed by yihui** 2018-01-16 06:11 UTC
