### ISSUE TITLE
Extension Fixed Header Doesn't Resize Properly

### ISSUE THREAD

**Issue by phillc73** [rstudio/DT#60] opened 2015-04-27 00:44 UTC
When using the FixedHeader extension, strange behaviour can be seen when resizing the browser window.

Example code:

```R
library("shiny")
library("DT")
library("datasets")

ui <- shinyUI(fluidPage(
  mainPanel(
    DT::dataTableOutput("mtcarsTable")
      )
  )
 )
)

server <- shinyServer(function(input, output) {
  output$mtcarsTable <- DT::renderDataTable({
    DT::datatable(datasets::mtcars,
                  extensions = 'FixedHeader'
                  )
    })
 }
)

shinyApp(ui, server)
```
And now two screen grabs. The first shows the page on initial load:
![screenshot - 270415 - 01 23 37](https://cloud.githubusercontent.com/assets/815126/7340079/1951e140-ec7d-11e4-890f-1355b89a213e.png)
The second screen grab shows the same page after expanding the width of the browser window:
![screenshot - 270415 - 01 24 04](https://cloud.githubusercontent.com/assets/815126/7340081/22bdb4ca-ec7d-11e4-9cca-9485519486d2.png)
As you can see, the columns have expanded, but the fixed header has remainded a little too fixed. My expectation was that the "FixedHeader" would also expand correctly when the page is resized.

The Fixed Header also remains when switching between tabs. Move to the second and third tab, using the example code below:

```R
library("shiny")
library("DT")
library("datasets")

ui <- shinyUI(fluidPage(
  mainPanel(
    tabsetPanel(
      tabPanel("Tab One", DT::dataTableOutput("mtcarsTable")),
      tabPanel("Tab Two"),
      tabPanel("Tab Three")
    )
  )
 )
)

server <- shinyServer(function(input, output) {
  output$mtcarsTable <- DT::renderDataTable({
    DT::datatable(datasets::mtcars,
                  extensions = 'FixedHeader'
                  )
    })
 }
)

shinyApp(ui, server)
```
Truly a fixed header!

I am using DT 0.0.38 and Firefox 37.0.2 in Linux, Debian 8.

**Comment by yihui** [comment] 2015-04-27 20:21
Thanks for the report. I can reproduce it, but unfortunately I guess it is not something I can fix on my side, since it looks like an issue from DataTables. You can reproduce it using the example on the DataTables website as well. You can open this page in a narrow browser window, and then make the window wider: http://datatables.net/release-datatables/extensions/FixedHeader/examples/simple.html You will see the fixed header is always fixed:

![screenshot from 2015-04-27 15 16 34](https://cloud.githubusercontent.com/assets/163582/7356884/d56a43e0-ecf0-11e4-8a3d-ef79a18acf35.png)

I guess you can report this to the author of DataTables.

**Comment by yihui** [comment] 2015-04-27 20:23
Oh for the second issue you mentioned, I guess it might be fixed by using a smaller z-index http://datatables.net/release-datatables/extensions/FixedHeader/examples/zIndexes.html

**Comment by phillc73** [comment] 2015-04-27 21:08
I've decided to avoid the FixedHeader extension. Using Scroller instead achieves a somewhat similar effect, with column labels always remaining visible.

**Closed** 2015-04-27 21:08 UTC
