### ISSUE TITLE
The "Buttons" extension trims downloaded files

### ISSUE THREAD

**Issue by nuno-agostinho** [rstudio/DT#340] opened 2016-08-10 12:59 UTC
Currently, it's not possible to download the whole table using the _Buttons_ extension from a table rendered through the `renderDataTable` function. Clicking one of the buttons (CSV, excel, PDF, …) outputs a file that only shows the currently displayed rows (10 by default). However, when using the example given in https://rstudio.github.io/DT/003-tabletools-buttons.html there are no issues retrieving the whole table.

See https://nuno-agostinho.shinyapps.io/DT_renderDataTable_download_bug/ to reproduce this issue.

**Comment by carlganz** [comment] 2016-08-10 14:33
It is possible to download the whole table. See this StackOverflow answer: http://stackoverflow.com/questions/38477345/r-dt-package-buttons-extension-download-button-with-scroller-downloads-only/

**Comment by nuno-agostinho** [comment] 2016-08-10 15:06
Thanks! Unfortunately, I can't use client-side DataTables since column filtering is really slow versus the server-side DataTables.

Also, this should be written in https://rstudio.github.io/DT.

**Comment by yihui** [comment] 2016-08-11 03:53
The server-side processing mode always fetches only one page of data a time, so DataTables only knows one page of data. When downloading the data, DataTables can only write out all the data it knows. By comparison, client-side tables have the full data live in the browser.

It might be possible to define a custom button to download the full data, but I need to learn more about it: https://datatables.net/extensions/buttons/custom

**Comment by merl-dev** [comment] 2016-09-27 14:53
Unfortunately setting `SERVER = FALSE` has not worked, and I still get only the current page.

**Comment by yihui** [comment] 2016-09-27 19:53
@merl-dev It is `server = FALSE`, instead of `SERVER`.

**Comment by merl-dev** [comment] 2016-09-28 05:24
@yihui just a typo, I was typing it in correctly in my code...

It would appear that the problem was where the `server=FALSE ` was placed:  
- `DT::renderDataTable(mytable, server = FALSE)` : works fine
- `datatable(mytable, extensions = 'Buttons', options  = list(server=FALSE, ...))` : doesn't work

**Comment by yihui** [comment] 2016-09-28 05:30
This page http://rstudio.github.io/DT/shiny.html, this http://rstudio.github.io/DT/server.html, and the R help page `?DT::renderDataTable` tell you where to put the `server` argument. I don't know where you saw `datatable(mytable, extensions = 'Buttons', options = list(server=FALSE, ...))`.

**Comment by yihui** [comment] 2018-01-04 23:35
Duplicate of #267

**Closed by yihui** 2018-01-04 23:35 UTC
