### ISSUE TITLE
Only 3 rows are shown instead of 10

### ISSUE THREAD

**Issue by jcheng5** [rstudio/DT#379] opened 2016-12-16 17:29 UTC
Running `DT::datatable(quakes)` in RStudio 1.0.136. Only 3 rows are shown of the datatable by default, not 10. Git bisect shows this issue to have been introduced by this commit:

76d95d08cf6011eb5c466a6c22b4ed39b5d48431

**Comment by vnijs** [comment] 2017-12-28 03:29
I'm also seeing this issue in the Rstudio Viewer using DT version 0.2 from CRAN. See screenshot below. Both `scrollX` and `scrollY` seem to be set but neither are set in my code (see also repex below).

![image](https://user-images.githubusercontent.com/2998956/34394977-1c19369e-eb12-11e7-9cfa-0ca4a6a4890a.png)

I installed the development version from github as well and it seems this might be related to the following lines:

https://github.com/rstudio/DT/blob/master/inst/htmlwidgets/datatables.js#L186-L188

However, when I set `options.scrollY = false;` scrolllX seems to be turned on even though I set it to it to FALSE in the call to `datatable`. Also, for some other DT tables in one of my apps no rows at are displayed (see screenshot below).

![image](https://user-images.githubusercontent.com/2998956/34395125-c6256cc0-eb12-11e7-8f8d-d48b85740bde.png)

Reproducible example below. `source` the code directly to the console rather than using the `Run App` button to see the effect. Same result with DT 0.2 and the latest from github. I'm using shiny 1.0.5 and rstudioapi 0.7. I don't know if this is a shiny, DT, or rstudioapi issue so I'm cc-ing @jcheng5 and @kevinushey as well

```
library(shiny)

ui = fluidPage(
  DT::dataTableOutput("tbl")
)

server = function(input, output, session) {
  output$tbl <- DT::renderDataTable(
    DT::datatable(
      mtcars, 
      filter = list(position = "top"), 
      style = "bootstrap",
      options = list(pageLength = 10)
    )
  )
}

## this function works fine, as does using the `Run App` button in Rstudio
# run <- function (url) {invisible(.Call("rs_shinyviewer", url, getwd(), 2))}

## both functions below produce a DT table with 2 or 3 rows
# run <- function(url) {rstudioapi::viewer(url, "maximize")}
run <- shiny::paneViewer(minHeight = "maximize")
shinyApp(ui = ui, server = server, options = list(launch.browser = run))
```

Screenshot:

![image](https://user-images.githubusercontent.com/2998956/34399324-36d3f554-eb3b-11e7-9a42-48c0da8730a7.png)

**Comment by yihui** [comment] 2018-01-05 16:22
Should be fixed now. Thanks for the report!

**Closed** 2018-01-05 16:22 UTC
Labels: bug

**Comment by vnijs** [comment] 2018-01-05 21:11
Thanks! As you mention in [543f29f](https://github.com/rstudio/DT/commit/543f29f187e4546efd69781ce3d2ca716de937ef), this still requires `fillContainer = FALSE` to work in Rstudio Viewer

**Comment by vnijs** [comment] 2018-01-05 21:49
FYI With DT 0.2.20, some tables now completely disappear when viewer in Chrome or Rstudio Viewer where they were shown fine with DT 0.2. This is in a large app so it will take me some time to create a reproducible example

Also, `fillContainer = FALSE` seems to fix the issue in DT 0.2 as well

**Comment by yihui** [comment] 2018-01-05 23:42
@vnijs Did you make sure to `library(DT)` after `library(shiny)`, or use the `DT::` qualifier before `dataTableOutput()` and `renderDataTable()`? In the most recent version, I added aliases `DTOutput()` and `renderDT()` to avoid this problem of name collisions.

**Comment by vnijs** [comment] 2018-01-06 19:31
I do use `DT::`. Thanks for checking. It seems dispatch works differently somehow with DT 0.2.20 vs DT 0.2 . As a work-around for https://github.com/yihui/knitr/issues/1399 I specify a method to render datatables inside a shiny app (see below). The function does nothing when used outside of the app (see below) to avoid having to change code used inside or outside the app.

This works fine with DT 0.2 but stopped working with DT 0.2.20. See reproducible example below. Let me know if you prefer I post this as a separate issue. Thanks

```
## works in DT 0.2 but not in DT 0.2.20
render(DT::datatable(mtcars))

## works in both DT 0.2 and DT 0.2.20
render.datatables(DT::datatable(mtcars))
```

Method defined in radiant.data

```
render <- function(object, ...) UseMethod("render", object)

render.datatables <- function(object, ...) {
  ## use renderDataTable only when in shiny app
  if (exists("r_environment")) {
    DT::renderDataTable(object)
  } else {
    object
  }
}
```

Reproducible example:

```
    library(shiny)
    library(DT)
    library(knitr)
    
    getdeps <- function() {
      htmltools::attachDependencies(
        htmltools::tagList(),
        c(htmlwidgets:::getDependency("datatables", "DT"))
      )
    }
    
    ## works in both DT 0.2 and DT 0.2.20
    chunk1 <- "
    ```{r, echo = TRUE}
    DT::renderDT(DT::datatable(mtcars))
    ````
    "
    
    ## works in both DT 0.2 and DT 0.2.20
    chunk2 <- "
    ```{r, echo = TRUE}
    render.datatables(DT::datatable(mtcars))
    ````
    "
    
    ## stopped working in DT 0.2.20
    chunk3 <- "
    ```{r, echo = TRUE}
    render(DT::datatable(mtcars))
    ````
    "
    
    ## which chunk to use
    chunk <- chunk3
    
    render <- function(object, ...) UseMethod("render", object)
    
    render.datatables <- function(object, ...) {
      DT::renderDataTable(object)
    }
    
    # render.shiny.render.function <- function(object, ...) object
    
    scrub <- function(x) {
      gsub("&lt;!&ndash;html_preserve&ndash;&gt;", "", x) %>%
      gsub("&lt;!&ndash;/html_preserve&ndash;&gt;", "", .)
    }
    
    ui = fluidPage(
      htmlOutput("knitted"),
      getdeps()
    )
    
    server = function(input, output, session) {
      output$knitted <- renderUI({
        knitr::knit2html(text = chunk, fragment.only = TRUE, stylesheet = "") %>%
          scrub() %>%
          HTML()
      })
    }
    
    shinyApp(ui = ui, server = server)
```

Output for chunk 3 when using DT 0.2.20

![image](https://user-images.githubusercontent.com/2998956/34643163-584df090-f2d4-11e7-8fb6-6205d2c1b139.png)

Output for chunk 3 when using DT 0.2

![image](https://user-images.githubusercontent.com/2998956/34643192-e3442642-f2d4-11e7-92d6-6b6769a1b7c1.png)

**Comment by yihui** [comment] 2018-01-17 03:53
@vnijs Your issue should be fixed now. Thanks!

**Comment by vnijs** [comment] 2018-01-17 05:08
Excellent! Thanks @yihui, this seems to fix the issue
